### ISSUE TITLE
feat(build): support building clice with GCC and MSVC

### ISSUE THREAD

**Issue by icysky404** [clice-io/clice#22]
I am currently trying to make the cmake build script more automated on handling dependencies. I've noticed that this project is using some aggressive C++ features like `static operator ()` which is not supported by MSVC yet. Is there any plan to support compilers other than clang (like MSVC and GCC)?

**Comment by heheda123123** [comment]
这应该无所谓把，不是库，编译出来用就行

**Comment by icysky404** [comment]
But anyway, we can make it a bit more contributor friendly, right?

**Comment by 16bit-ykiko** [comment]
Because I was the only one developing in the past, I planned to postpone the compatibility work for later. However, it seems that many people are interested in contributing recently, so I will make changes to the code to ensure it can compile successfully on GCC and MSVC, and provide a detailed configuration document.

**Comment by icysky404** [comment]
Thanks.
